//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_slork2019 p_slork2019;
        
        public static SteamVR_Input_ActionSet_slork2019 slork2019
        {
            get
            {
                return SteamVR_Actions.p_slork2019.GetCopy<SteamVR_Input_ActionSet_slork2019>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_slork2019 = ((SteamVR_Input_ActionSet_slork2019)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_slork2019>("/actions/slork2019")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.slork2019};
        }
    }
}
