//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_slork2019 : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean ChargeWind
        {
            get
            {
                return SteamVR_Actions.slork2019_ChargeWind;
            }
        }
        
        public virtual SteamVR_Action_Boolean AdvanceToNextPart
        {
            get
            {
                return SteamVR_Actions.slork2019_AdvanceToNextPart;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.slork2019_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean PlayLightning
        {
            get
            {
                return SteamVR_Actions.slork2019_PlayLightning;
            }
        }
        
        public virtual SteamVR_Action_Boolean OverrideWindToPlotLocation
        {
            get
            {
                return SteamVR_Actions.slork2019_OverrideWindToPlotLocation;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.slork2019_Haptic;
            }
        }
    }
}
